// <auto-generated />
using System;
using Mc2.CrudTest.Infrastructure.Persistence.Sqlite.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Faratechno.Infrastructure.HR.Persistence.Sqlite.Migrations
{
    [DbContext(typeof(SqliteCommandDbContext))]
    partial class SqliteCommandDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
        }
    }
}
